---
services:
- module: passfail
  criterias:
  - class: bzt.modules.monitoring.MonitoringCriteria
    My Message: CPU on local server>6% for 7s, stop as failed
    subject: local/cpu
    condition: '>'
    threshold: 6
    timeframe: 7s
